@startuml
!include <cloudinsight/kafka>
!include <cloudinsight/postgresql>
!theme cerulean

skinparam defaultTextAlignment center
skinparam backgroundColor white

participant "syfo-dokumentaporten" as api
participant "Maskinporten" as maskinporten
participant "Alitinn auth" as altinn
participant "Dialogporten" as dialogporten
participant "LPS" as lps
api -> maskinporten : Request access token
api -> altinn : Exchange token for Altinn token
api -> dialogporten : Post dialog with for employee (on sick leave)
api -> dialogporten : Post transmission with link do document
lps -> maskinporten : Get System user token
lps -> altinn : Exchange token for Altinn token
lps -> dialogporten : GET /api/v1/enduser/dialogs
lps -> dialogporten : GET /api/v1/enduser/dialogs/{dialogId}
lps -> api : GET /api/v1/documents/{id}
lps -> api : GET /api/v1/documents/{id}/meta
@enduml
