name: Build and deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [ checks_requested ]
  workflow_dispatch:

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/jar-app.yaml@main
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: syfo-dokumentporten
      java-version: '21'

  deploy-alert-prod:
    if: github.ref_name == 'main'
    name: Deploy alert to prod
    runs-on: ubuntu-latest
    needs:
      - jar-app
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/alert.yaml
